### ISSUE TITLE
Duplicate stars detected

### ISSUE THREAD

**Issue by aaronwmorris** [Curtis2012/clearskyalarm#3]
This star detection method works very well.  Better than all of the others I have tested.  However, I found that using this method, I was still getting duplicates.

PR #2 compares each point to all of the existing stars and this appears to eliminate all of the duplicate detections.  I am sure there is a better way to code this, but it works.  :-)

**Comment by aaronwmorris** [comment]
By the way, I am the author of https://github.com/aaronwmorris/indi-allsky/ which is similar to Thomas Jacquin's allsky software, except written completely in Python.

**Comment by Curtis2012** [comment]
> This star detection method works very well. Better than all of the others I have tested. However, I found that using this method, I was still getting duplicates.
> 
> PR #2 compares each point to all of the existing stars and this appears to eliminate all of the duplicate detections. I am sure there is a better way to code this, but it works. :-)

Arron, 

Yes, there are duplicates with this method, but for my purposes I was only interested in a gross count of stars not an accurate one. My objective was to generate a notification if there were "a lot" of stars visible in the sky, an exact count was not necessary for this purpose. I did include the "detectionDistance" parameter to reduce the number of duplicates. 

I will take a look at your PR and your AllSky code. 

Thanks!,

Curtis

**Comment by Curtis2012** [comment]
> By the way, I am the author of https://github.com/aaronwmorris/indi-allsky/ which is similar to Thomas Jacquin's allsky software, except written completely in Python.

I like the fact that your allskycam uses indi. Has anyone used that interface to do interesting things with your allskycam system...like fire up their astrophotography gear to start imaging?

**Comment by aaronwmorris** [comment]
This is something I may end up doing long term.  Currently,  I am focused on extracting as much data about the sky as possible:  brightness, star count, anything that indicates what is going on in the sky to help with my astrophotography.  I already extensively use my all sky cameras to monitor sky quality during my sessions.

Long term, I will be interested in more integrations and using indi-allsky to directly integrate with the imaging sessions.
