### ISSUE TITLE
detected file create with very large rectangles

### ISSUE THREAD

**Issue by Curtis2012** [Curtis2012/clearskyalarm#4]
Arron,

The revised detection algorithm appears to work well, but results in very large rectangles being drawn in the detected image file. Example allskycam image and resulting detected file attached.

![image-test-02](https://user-images.githubusercontent.com/41484582/140644587-2b995c90-43e3-4efa-bf2f-f85690426685.jpg)
![detected-image-test-02](https://user-images.githubusercontent.com/41484582/140644589-834561e0-bee2-4bcf-b000-dacd48229e80.jpg)
 
 @aaronwmorris

**Comment by aaronwmorris** [comment]
I think I see the problem.  I will submit a new PR in a few.

I did not actually run your code, I copied some of the bits out into my own script.  I had my own code to draw circles around the detected stars.

**Comment by Curtis2012** [comment]
Good, thanks!

**Comment by aaronwmorris** [comment]
PR #5 should fix this problem

**Comment by Curtis2012** [comment]
> PR #5 should fix this problem

Thanks, will review.
